### ISSUE TITLE
Script crashing

### ISSUE THREAD

**Issue by devikasondhi** [codingsoo/ARAT-RL#3]
Hello,

I'm seeing the following traceback error when trying to run on lanuage api

```
Traceback (most recent call last):
  File "C:\Users\0010DE744\Desktop\Projects\ApiTesting\APITTest_Research\ARAT-RL\arat-rl.py", line 751, in <module>
    main()
  File "C:\Users\0010DE744\Desktop\Projects\ApiTesting\APITTest_Research\ARAT-RL\arat-rl.py", line 720, in main
    update_q_table(q_table, alpha, gamma, selected_operation, selected_parameters, response, path, query_params, body_params)
  File "C:\Users\0010DE744\Desktop\Projects\ApiTesting\APITTest_Research\ARAT-RL\arat-rl.py", line 432, in update_q_table
    keys_list = list(selected_parameters.keys())
AttributeError: 'list' object has no attribute 'keys'
```

Command used:
```
python arat-rl.py spec/languagetool.yaml http://localhost:8081/v2 240
```

Am I passing anything incorrect here? The API is running fine.

**Comment by codingsoo** [comment]
Hello @devikasondhi , thank you for the report! I just made an update to resolve the issue. Please reopen this issue if you still have the issue!
